defmodule Rindle.Upload.Broker do
  @moduledoc """
  Manages direct-to-storage upload sessions.
  """

  alias Rindle.Domain.{MediaAsset, MediaUploadSession}
  alias Rindle.Repo
  alias Rindle.Security.StorageKey
  alias Rindle.Domain.UploadSessionFSM
  alias Rindle.Domain.AssetFSM

  @doc """
  Initiates a new direct upload session.
  Creates a staged MediaAsset and an initialized MediaUploadSession.
  """
  def initiate_session(profile_module, opts \\ []) do
    profile_name = profile_module_to_name(profile_module)
    filename = Keyword.get(opts, :filename, "unknown")
    extension = Path.extname(filename)

    # We generate a unique storage key upfront for the direct upload
    # Since we don't have the asset ID yet (will be generated by DB),
    # we use a temporary placeholder or generate the ID ourselves.
    asset_id = Ecto.UUID.generate()
    storage_key = StorageKey.generate(profile_name, asset_id, extension)

    expires_in_seconds = Keyword.get(opts, :expires_in, 3600)
    expires_at = DateTime.add(DateTime.utc_now(), expires_in_seconds, :second)

    case Repo.transaction(fn ->
           {:ok, asset} =
             %MediaAsset{id: asset_id}
             |> MediaAsset.changeset(%{
               state: "staged",
               profile: profile_name,
               storage_key: storage_key,
               filename: filename
             })
             |> Repo.insert()

           {:ok, session} =
             %MediaUploadSession{}
             |> MediaUploadSession.changeset(%{
               asset_id: asset.id,
               state: "initialized",
               upload_key: storage_key,
               expires_at: expires_at
             })
             |> Repo.insert()

           session
         end) do
      {:ok, session} ->
        :telemetry.execute(
          [:rindle, :upload, :start],
          %{system_time: System.system_time()},
          %{
            profile: profile_name,
            adapter: profile_module.storage_adapter(),
            session_id: session.id
          }
        )

        {:ok, session}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Generates a presigned URL for an initialized session.
  Transitions session state to `signed`.
  """
  def sign_url(session_id, opts \\ []) do
    with %MediaUploadSession{} = session <- Repo.get(MediaUploadSession, session_id),
         :ok <- UploadSessionFSM.transition(session.state, "signed", %{session_id: session.id}),
         asset <- Repo.preload(session, :asset).asset,
         profile_module <- profile_name_to_module(asset.profile),
         adapter <- profile_module.storage_adapter(),
         expires_in <- Keyword.get(opts, :expires_in, 3600),
         {:ok, presigned} <- adapter.presigned_put(session.upload_key, expires_in, opts) do
      Repo.transaction(fn ->
        {:ok, updated_session} =
          session
          |> MediaUploadSession.changeset(%{state: "signed"})
          |> Repo.update()

        %{session: updated_session, presigned: presigned}
      end)
    else
      nil -> {:error, :not_found}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Verifies that a direct upload was completed in storage.
  Transitions session to `completed` and asset to `validating`.
  """
  def verify_completion(session_id, opts \\ []) do
    with %MediaUploadSession{} = session <- Repo.get(MediaUploadSession, session_id),
         asset <- Repo.preload(session, :asset).asset,
         profile_module <- profile_name_to_module(asset.profile),
         adapter <- profile_module.storage_adapter(),
         # Check storage for object existence (Pitfall 5)
         {:ok, metadata} <- adapter.head(session.upload_key, opts),
         :ok <- UploadSessionFSM.transition(session.state, "verifying", %{session_id: session.id}),
         :ok <- AssetFSM.transition(asset.state, "validating", %{asset_id: asset.id}) do
      Ecto.Multi.new()
      |> Ecto.Multi.update(
        :session,
        MediaUploadSession.changeset(session, %{
          state: "completed",
          verified_at: DateTime.utc_now()
        })
      )
      |> Ecto.Multi.update(
        :asset,
        MediaAsset.changeset(asset, %{
          state: "validating",
          byte_size: Map.get(metadata, :size),
          content_type: Map.get(metadata, :content_type)
        })
      )
      |> Oban.insert(:promote_job, Rindle.Workers.PromoteAsset.new(%{asset_id: asset.id}))
      |> Repo.transaction()
      |> case do
        {:ok, %{session: updated_session, asset: updated_asset}} ->
          :telemetry.execute(
            [:rindle, :upload, :stop],
            %{system_time: System.system_time()},
            %{
              profile: asset.profile,
              adapter: profile_module.storage_adapter(),
              session_id: updated_session.id,
              asset_id: updated_asset.id
            }
          )

          {:ok, %{session: updated_session, asset: updated_asset}}

        {:error, _name, reason, _changes} ->
          {:error, reason}
      end
    else
      nil -> {:error, :not_found}
      {:error, :not_found} -> {:error, :storage_object_missing}
      {:error, reason} -> {:error, reason}
    end
  end

  defp profile_module_to_name(module) do
    to_string(module)
  end

  defp profile_name_to_module(name) do
    String.to_existing_atom(name)
  rescue
    _ -> nil
  end
end
