defmodule Rindle.Upload.Broker do
  @moduledoc """
  Manages direct-to-storage upload sessions.
  """

  alias Rindle.Domain.AssetFSM
  alias Rindle.Domain.{MediaAsset, MediaUploadSession}
  alias Rindle.Domain.UploadSessionFSM
  alias Rindle.Repo
  alias Rindle.Security.StorageKey
  alias Rindle.Workers.PromoteAsset

  @doc """
  Initiates a new direct upload session.

  Creates a staged `MediaAsset` and an `initialized` `MediaUploadSession` in
  a single DB transaction, then emits `[:rindle, :upload, :start]`
  telemetry AFTER commit.

  ## Examples

      # Requires Rindle.Repo running and a profile module.
      iex> {:ok, session} = Rindle.Upload.Broker.initiate_session(MyApp.MediaProfile, filename: "photo.png")
      iex> session.state
      "initialized"

  """
  def initiate_session(profile_module, opts \\ []) do
    profile_name = profile_module_to_name(profile_module)
    filename = Keyword.get(opts, :filename, "unknown")
    extension = Path.extname(filename)

    # We generate a unique storage key upfront for the direct upload
    # Since we don't have the asset ID yet (will be generated by DB),
    # we use a temporary placeholder or generate the ID ourselves.
    asset_id = Ecto.UUID.generate()
    storage_key = StorageKey.generate(profile_name, asset_id, extension)

    expires_in_seconds = Keyword.get(opts, :expires_in, 3600)
    expires_at = DateTime.add(DateTime.utc_now(), expires_in_seconds, :second)

    case Repo.transaction(fn ->
           {:ok, asset} =
             %MediaAsset{id: asset_id}
             |> MediaAsset.changeset(%{
               state: "staged",
               profile: profile_name,
               storage_key: storage_key,
               filename: filename
             })
             |> Repo.insert()

           {:ok, session} =
             %MediaUploadSession{}
             |> MediaUploadSession.changeset(%{
               asset_id: asset.id,
               state: "initialized",
               upload_key: storage_key,
               expires_at: expires_at
             })
             |> Repo.insert()

           session
         end) do
      {:ok, session} ->
        :telemetry.execute(
          [:rindle, :upload, :start],
          %{system_time: System.system_time()},
          %{
            profile: profile_name,
            adapter: profile_module.storage_adapter(),
            session_id: session.id
          }
        )

        {:ok, session}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Generates a presigned URL for an initialized session.

  Transitions the session to `signed` and returns
  `{:ok, %{session: %MediaUploadSession{}, presigned: %{url: String.t()}}}`.

  ## Examples

      # Requires Rindle.Repo + a configured S3-compatible storage adapter.
      iex> {:ok, %{session: session, presigned: %{url: url}}} =
      ...>   Rindle.Upload.Broker.sign_url(session_id)
      iex> session.state
      "signed"
      iex> is_binary(url)
      true

  """
  def sign_url(session_id, opts \\ []) do
    with %MediaUploadSession{} = session <- Repo.get(MediaUploadSession, session_id),
         :ok <- UploadSessionFSM.transition(session.state, "signed", %{session_id: session.id}),
         asset <- Repo.preload(session, :asset).asset,
         {:ok, profile_module} <- profile_name_to_module(asset.profile),
         adapter <- profile_module.storage_adapter(),
         expires_in <- Keyword.get(opts, :expires_in, 3600),
         {:ok, presigned} <- adapter.presigned_put(session.upload_key, expires_in, opts) do
      Repo.transaction(fn ->
        {:ok, updated_session} =
          session
          |> MediaUploadSession.changeset(%{state: "signed"})
          |> Repo.update()

        %{session: updated_session, presigned: presigned}
      end)
    else
      nil -> {:error, :not_found}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Verifies that a direct upload was completed in storage.

  Transitions the session to `completed` and the asset to `validating`,
  then enqueues `PromoteAsset`. Emits
  `[:rindle, :upload, :stop]` telemetry AFTER the `Ecto.Multi` commits.

  ## Examples

      # Requires Rindle.Repo + the upload object to exist in storage.
      iex> {:ok, %{session: session, asset: asset}} =
      ...>   Rindle.Upload.Broker.verify_completion(session_id)
      iex> session.state
      "completed"
      iex> asset.state
      "validating"

  """
  def verify_completion(session_id, opts \\ []) do
    with %MediaUploadSession{} = session <- Repo.get(MediaUploadSession, session_id),
         asset <- Repo.preload(session, :asset).asset,
         {:ok, profile_module} <- profile_name_to_module(asset.profile),
         adapter <- profile_module.storage_adapter(),
         # Check storage for object existence (Pitfall 5)
         {:ok, metadata} <- adapter.head(session.upload_key, opts),
         :ok <- UploadSessionFSM.transition(session.state, "verifying", %{session_id: session.id}),
         :ok <- AssetFSM.transition(asset.state, "validating", %{asset_id: asset.id}) do
      execute_verify_completion(session, asset, profile_module, metadata)
    else
      nil -> {:error, :not_found}
      {:error, :not_found} -> {:error, :storage_object_missing}
      {:error, reason} -> {:error, reason}
    end
  end

  defp execute_verify_completion(session, asset, profile_module, metadata) do
    Ecto.Multi.new()
    |> Ecto.Multi.update(
      :verifying_session,
      MediaUploadSession.changeset(session, %{state: "verifying"})
    )
    |> Ecto.Multi.run(:verify_fsm_complete, fn _repo, %{verifying_session: vs} ->
      do_fsm_transition(vs)
    end)
    |> Ecto.Multi.update(
      :session,
      fn %{verifying_session: vs} ->
        MediaUploadSession.changeset(vs, %{
          state: "completed",
          verified_at: DateTime.utc_now()
        })
      end
    )
    |> Ecto.Multi.update(
      :asset,
      MediaAsset.changeset(asset, %{
        state: "validating",
        byte_size: Map.get(metadata, :size),
        content_type: Map.get(metadata, :content_type)
      })
    )
    |> Oban.insert(:promote_job, PromoteAsset.new(%{asset_id: asset.id}))
    |> Repo.transaction()
    |> case do
      {:ok, %{session: updated_session, asset: updated_asset}} ->
        :telemetry.execute(
          [:rindle, :upload, :stop],
          %{system_time: System.system_time()},
          %{
            profile: asset.profile,
            adapter: profile_module.storage_adapter(),
            session_id: updated_session.id,
            asset_id: updated_asset.id
          }
        )

        {:ok, %{session: updated_session, asset: updated_asset}}

      {:error, _name, reason, _changes} ->
        {:error, reason}
    end
  end

  defp do_fsm_transition(vs) do
    case UploadSessionFSM.transition(vs.state, "completed", %{session_id: vs.id}) do
      :ok -> {:ok, :transitioned}
      err -> err
    end
  end

  defp profile_module_to_name(module) do
    to_string(module)
  end

  defp profile_name_to_module(name) do
    {:ok, String.to_existing_atom(name)}
  rescue
    ArgumentError -> {:error, :unknown_profile}
  end
end
