defmodule Rindle.Brandbook.AdminDesignSystemValidationTest do
  use ExUnit.Case, async: false

  @moduletag :integration

  @repo_root Path.expand("../..", __DIR__)

  @implementation_files [
    "brandbook/src/admin-design-system-data.mjs",
    "brandbook/src/admin-css-build.mjs",
    "brandbook/src/admin-contrast.mjs",
    "brandbook/src/admin-gallery.mjs",
    "brandbook/src/admin-gallery-check.mjs",
    "brandbook/admin-gallery/index.html",
    "brandbook/tokens/rindle-admin.css"
  ]

  @screenshots [
    "gallery-light-desktop.png",
    "gallery-dark-desktop.png",
    "gallery-auto-desktop.png",
    "gallery-light-mobile.png",
    "status-chips-dark.png",
    "theme-picker-light.png",
    "confirm-dialog-light.png"
  ]

  test "DS-01 generated admin CSS is reproducible and token-backed" do
    output = run_node("brandbook/src/admin-css-build.mjs")
    assert output =~ "rindle-admin.css written"
    assert output =~ "parity OK"

    css = read!("brandbook/tokens/rindle-admin.css")

    assert css =~
             "generated by brandbook/src/admin-css-build.mjs from tokens.json - do not edit by hand"

    for selector <- [
          ".rindle-admin-shell",
          ".rindle-admin-nav__item",
          ".rindle-admin-table__row",
          ".rindle-admin-status-chip--ready",
          ".rindle-admin-status-chip--processing",
          ".rindle-admin-status-chip--warning",
          ".rindle-admin-status-chip--danger",
          ".rindle-admin-status-chip--quarantine",
          ".rindle-admin-status-chip--info",
          ".rindle-admin-button--primary",
          ".rindle-admin-button--secondary",
          ".rindle-admin-button--quiet",
          ".rindle-admin-button--destructive",
          ".rindle-admin-confirm-dialog",
          ".rindle-admin-drawer",
          ".rindle-admin-toast",
          ".rindle-admin-empty-state",
          ".rindle-admin-skeleton"
        ] do
      assert css =~ selector
    end

    for expected <- [
          ":root",
          "[data-theme=\"dark\"]",
          "[data-theme=\"auto\"]",
          "prefers-color-scheme: dark",
          "prefers-reduced-motion",
          "--rindle-focus-width",
          "--rindle-focus-offset",
          "--rindle-focus-ring",
          "--rindle-motion-press",
          "--rindle-motion-popover",
          "--rindle-motion-toast",
          "--rindle-motion-transition",
          "--rindle-motion-easing",
          "var(--rindle-"
        ] do
      assert css =~ expected
    end

    assert_generated_clean(["brandbook/tokens/rindle-admin.css"])
  end

  test "DS-03 admin and base contrast gates cover required token pairs" do
    data = read!("brandbook/src/admin-design-system-data.mjs")
    assert data =~ "CONSOLE_CONTRAST_PAIRS"
    assert data =~ "status-processing"

    for context <- [
          "buttons",
          "table",
          "focus",
          "status chips",
          "toasts",
          "confirm dialog",
          "drawer",
          "empty state",
          "skeleton",
          "borders"
        ] do
      assert data =~ context
    end

    admin_output = run_node("brandbook/src/admin-contrast.mjs")
    assert admin_output =~ "status chips processing"
    assert admin_output =~ "admin contrast: 44/44 pairs pass"

    base_output = run_node("brandbook/src/contrast.mjs")
    assert base_output =~ "47/47 pairs pass"
  end

  test "DS-02 gallery harness proves themes, screenshots, and surface anchors" do
    output = run_node("brandbook/src/admin-gallery-check.mjs")
    assert output =~ "admin gallery check passed - 7 screenshots written"

    html = read!("brandbook/admin-gallery/index.html")
    assert html =~ "data-theme=\"auto\""
    assert html =~ "data-rindle-admin-root"
    assert html =~ "owner:cohort-demo-42"

    for theme <- ["light", "dark", "auto"] do
      assert html =~ "data-rindle-admin-theme=\"#{theme}\""
    end

    for component <- [
          "shell",
          "nav",
          "table",
          "status-chips",
          "buttons",
          "theme-picker",
          "confirm-dialog",
          "drawer",
          "toasts",
          "empty-state",
          "skeletons"
        ] do
      assert html =~ "data-rindle-admin-component=\"#{component}\""
    end

    for {surface, id} <- [
          {"Home/Status", "home-status"},
          {"Assets", "assets"},
          {"Upload Sessions", "upload-sessions"},
          {"Variants/Jobs", "variants-jobs"},
          {"Runtime/Doctor", "runtime-doctor"},
          {"Actions", "actions"}
        ] do
      assert html =~ "data-rindle-admin-surface=\"#{surface}\""
      assert html =~ "id=\"#{id}\""
      assert html =~ "href=\"##{id}\""
    end

    for screenshot <- @screenshots do
      path = path("brandbook/admin-gallery/screenshots/#{screenshot}")
      assert File.exists?(path), "expected #{path} to exist"
      assert File.stat!(path).size > 0, "expected #{path} to be non-empty"
    end

    assert_generated_clean([
      "brandbook/tokens/rindle-admin.css",
      "brandbook/admin-gallery/index.html"
    ])
  end

  test "ADMIN-02 boundary guide and implementation avoid host UI dependencies" do
    guide = read!("guides/admin_design_system.md")

    for command <- [
          "node brandbook/src/admin-css-build.mjs",
          "node brandbook/src/admin-contrast.mjs",
          "node brandbook/src/admin-gallery.mjs",
          "node brandbook/src/admin-gallery-check.mjs",
          "node brandbook/src/contrast.mjs"
        ] do
      assert guide =~ command
    end

    for expected <- [
          "brandbook/tokens/rindle-admin.css",
          "brandbook/admin-gallery/index.html",
          "brandbook/admin-gallery/screenshots/",
          "data-theme=\"light|dark|auto\"",
          "prefers-color-scheme",
          "Package Boundary",
          "priv/static/rindle_admin",
          "Rindle.Admin.Router.rindle_admin/2",
          "Rindle.Admin.Queries",
          "Tailwind",
          "daisyUI",
          "esbuild",
          "shadcn",
          "Radix",
          "Tailwind UI",
          "daisyUI registry",
          "third-party UI registries"
        ] do
      assert guide =~ expected
    end

    forbidden =
      ~r/tailwind|daisy|shadcn|radix|@apply|class="[^"]*(btn|card)|\.dark|theme-dark|host asset-pipeline/i

    matches =
      for file <- @implementation_files,
          body = read!(file),
          Regex.match?(forbidden, body),
          do: file

    assert matches == []

    assert read!("mix.exs") =~ "priv/static/rindle_admin"

    assert read!("priv/static/rindle_admin/rindle-admin.css") ==
             read!("brandbook/tokens/rindle-admin.css")
  end

  defp run_node(script) do
    node = System.find_executable("node") || flunk("node executable is required for #{script}")

    {output, status} =
      System.cmd(node, [script],
        cd: @repo_root,
        stderr_to_stdout: true
      )

    assert status == 0, """
    expected node #{script} to exit 0, got #{status}

    #{output}
    """

    output
  end

  defp assert_generated_clean(paths) do
    {output, status} =
      System.cmd("git", ["diff", "--exit-code", "--"] ++ paths,
        cd: @repo_root,
        stderr_to_stdout: true
      )

    assert status == 0, """
    generated artifacts changed after regeneration:

    #{output}
    """
  end

  defp read!(relative_path), do: relative_path |> path() |> File.read!()
  defp path(relative_path), do: Path.join(@repo_root, relative_path)
end
