// Shared geometry + palette constants for Rindle logo generation.
// All coordinates assume fontSize = 100: baseline at y = 0, negative y is up.
// Space Grotesk Medium @100: x-height 49.3, ascender (d/l) 70, stem width 10.3.

export const PALETTE = {
  ink: '#101417',
  deep: '#123A35', // Deep Current
  green: '#32D08C', // Rindle Green
  lime: '#CFEF6A', // Rind Lime
  shell: '#F7F4EA', // Warm Shell
  porcelain: '#FBFEFC',
};

export const FONT_SIZE = 100;
export const X_HEIGHT = 49.3;
export const ASCENDER = 70;
export const STEM = 10.3;

// Lockup spacing: logotype sits tight to the mark (~0.3x ascender, tuned optically).
export const MARK_GAP = 21;

// Padding around the composed artwork inside the viewBox.
export const PAD = 12;

export function svgDoc({ width, height, body, title, desc }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by brandbook/src/build.mjs - edit candidates.mjs or geometry.mjs, not this file -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${r2(width)} ${r2(height)}" role="img" aria-labelledby="t">
  <title id="t">${title}</title>
  <desc>${desc}</desc>
${body}
</svg>
`;
}

export function r2(n) {
  return Math.round(n * 100) / 100;
}
