// Generates tokens.css from tokens.json (lockstep) and verifies parity.
// Run: node tokens-build.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = join(here, '..', 'tokens');
const T = JSON.parse(readFileSync(join(tokensDir, 'tokens.json'), 'utf8'));

const raw = T.color.raw;
const deref = (v) => v.replace(/\{([a-z0-9-]+)\}/g, (_, k) => {
  if (!(k in raw)) throw new Error(`unknown raw token reference: {${k}}`);
  return raw[k];
});

let css = `/* generated by brandbook/src/tokens-build.mjs from tokens.json - do not edit by hand */

:root {
`;
for (const [k, v] of Object.entries(raw)) css += `  --rindle-${k}: ${v};\n`;
css += '\n  /* semantic roles (light) */\n';
for (const [k, v] of Object.entries(T.color.semantic.light)) css += `  --rindle-${k}: ${deref(v)};\n`;
css += '\n  /* typography */\n';
for (const [k, v] of Object.entries(T.typography.family)) css += `  --rindle-font-${k}: ${v.replace(/"/g, "'")};\n`;
for (const [k, v] of Object.entries(T.typography.scale)) {
  css += `  --rindle-text-${k}-size: ${v.size};\n  --rindle-text-${k}-line: ${v.line};\n  --rindle-text-${k}-weight: ${v.weight};\n`;
}
css += '\n  /* spacing */\n';
for (const [k, v] of Object.entries(T.spacing)) css += `  --rindle-space-${k}: ${v};\n`;
css += '\n  /* radii */\n';
for (const [k, v] of Object.entries(T.radius)) css += `  --rindle-radius-${k}: ${v};\n`;
css += '\n  /* borders, shadow, focus, motion */\n';
for (const [k, v] of Object.entries(T.border)) if (typeof v === 'string') css += `  --rindle-border-rule-${k}: ${deref(v)};\n`;
css += `  --rindle-shadow-card: ${T.shadow.card};\n`;
css += `  --rindle-focus-width: ${T.focus.width};\n  --rindle-focus-offset: ${T.focus.offset};\n`;
for (const [k, v] of Object.entries(T.motion)) {
  if (k === 'rules') continue;
  css += `  --rindle-motion-${k}: ${v};\n`;
}
css += `}

/* dark mode: opt-in via [data-theme="dark"], or automatic via media query on
   [data-theme="auto"] scopes */
[data-theme="dark"] {
`;
for (const [k, v] of Object.entries(T.color.semantic.dark)) css += `  --rindle-${k}: ${deref(v)};\n`;
css += `}

@media (prefers-color-scheme: dark) {
  [data-theme="auto"] {
`;
for (const [k, v] of Object.entries(T.color.semantic.dark)) css += `    --rindle-${k}: ${deref(v)};\n`;
css += `  }
}
`;

writeFileSync(join(tokensDir, 'tokens.css'), css);

// parity check: every raw + light-semantic token appears in the CSS exactly once
const written = readFileSync(join(tokensDir, 'tokens.css'), 'utf8');
const missing = [];
for (const k of [...Object.keys(raw), ...Object.keys(T.color.semantic.light)]) {
  if (!written.includes(`--rindle-${k}:`)) missing.push(k);
}
if (missing.length) {
  console.error('parity FAIL, missing:', missing.join(', '));
  process.exit(1);
}
console.log(`tokens.css written - ${Object.keys(raw).length} raw + ${Object.keys(T.color.semantic.light).length} semantic tokens, parity OK`);
